# Generated by Django 5.1.6 on 2025-03-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
