# Generated by Django 5.1.6 on 2025-03-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0002_telegramuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
