# Generated by Django 5.1.6 on 2025-03-11 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0003_alter_telegramuser_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_point', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('cashout_multiplier', models.FloatField(blank=True, null=True)),
                ('is_won', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniapp.telegramuser')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniapp.crashgame')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'game'], name='miniapp_bet_user_id_7bf0ee_idx')],
            },
        ),
    ]
