# Generated by Django 5.1.6 on 2025-03-11 19:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0004_crashgame_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
