# Generated by Django 5.1.6 on 2025-03-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0005_alter_telegramuser_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crashgame',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='crashgame',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='crashgame',
            name='crash_point',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
